#! /bin/bash
#echo .env >  
docker build -t tzpg/server:latest .
#docker build -t milleinnovacion/metadataimagemicroservice:latest --build-arg ssh_prv_key="$(cat ~/.ssh/id_rsa)" --build-arg ssh_pub_key="$(cat ~/.ssh/id_rsa.pub)" .